name: cross-compile
on:
  push:
    branches:
      - main
env:
  APP_NAME: BULL

jobs:
  # android:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4

  #     - uses: actions/setup-java@v4
  #       with:
  #         distribution: 'zulu'
  #         java-version: '17'

  #     - uses: subosito/flutter-action@v2
  #       with:
  #         channel: stable
  #         flutter-version: 3.24.5

  #     - uses: dtolnay/rust-toolchain@master
  #       with:
  #         toolchain: nightly
  #         components: llvm-tools-preview
    
  #     - run: flutter pub get
  #     - run: dart run build_runner build --delete-conflicting-outputs
  #     - run: flutter build apk
    
  #     - name: Upload artifact 
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: android_${{ env.APP_NAME }}
  #         path: build/app/outputs/flutter-apk/app-release.apk

  ios:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4

    - uses: dtolnay/rust-toolchain@stable

    - run: rustup target add aarch64-apple-ios

    - uses: subosito/flutter-action@v2
      with:
        channel: stable
        flutter-version: 3.24.5
        architecture: x64

    - run: flutter pub get
    - run: dart run build_runner build --delete-conflicting-outputs

    - name: Build no-codesign release
      run: flutter build ios --release --no-codesign
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ios_${{ env.APP_NAME }}
        path: build/ios/iphoneos/Runner.app
